apiVersion: ai.sap.com/v1alpha1
kind: Scenario
metadata:
  name: hello-world-docker-scenario
spec:
  steps:
    - name: print-hello
      image: docker.io/shirke0706/hello-world-app:latest
        command:
        - python3
        - '-c'
      args:
       - |
        print("Hello from Intellect Bizware Pvt Ltd") 
